import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit https://github.com/llimllib/nbastats
*/
`;

const prod = process.argv[2] === "production";

const sharedConfig = {
  banner: {
    js: banner,
  },
  bundle: true,
  external: [],
  format: "cjs",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: true,
};

Promise.all([
  esbuild.build({
    ...sharedConfig,
    entryPoints: ["src/index.ts"],
    target: "es2020",
    outfile: "dist/index.js",
    define: {
      "process.env.DATA_URL":
        JSON.stringify(process.env.DATA_URL) ||
        '"https://llimllib.github.io/nba_data"',
    },
  }),
  esbuild.build({
    ...sharedConfig,
    entryPoints: ["teamdiamond/index.ts"],
    target: "es2020",
    outfile: "dist/teams/index.js",
    define: {
      "process.env.DATA_URL":
        JSON.stringify(process.env.DATA_URL) ||
        '"https://llimllib.github.io/nba_data"',
    },
  }),
]).catch(() => process.exit(1));
