export type StatMeta = {
  name: string;
  type: FieldType;
  comment?: string;
};

export type StatDict = {
  [key: string]: StatMeta;
};

export enum FieldType {
  String,
  Int,
  Float,
  Year,
}

export const Fields: StatDict = {
  PLAYER_ID: { name: "PLAYER_ID", type: FieldType.Int },
  PLAYER_NAME: { name: "PLAYER_NAME", type: FieldType.String },
  NICKNAME: { name: "NICKNAME", type: FieldType.String },
  TEAM_ID: { name: "TEAM_ID", type: FieldType.Int },
  TEAM_ABBREVIATION: { name: "TEAM_ABBREVIATION", type: FieldType.String },
  AGE: { name: "AGE", type: FieldType.Float },
  GP: { name: "GP", type: FieldType.Int },
  W: { name: "W", type: FieldType.Int },
  L: { name: "L", type: FieldType.Int },
  W_PCT: { name: "W_PCT", type: FieldType.Float },
  MIN: { name: "MIN", type: FieldType.Float },
  FGM: { name: "FGM", type: FieldType.Int },
  FGA: { name: "FGA", type: FieldType.Int },
  FG_PCT: { name: "FG_PCT", type: FieldType.Float },
  FG3M: { name: "FG3M", type: FieldType.Int },
  FG3A: { name: "FG3A", type: FieldType.Int },
  FG3_PCT: { name: "FG3_PCT", type: FieldType.Float },
  FTM: { name: "FTM", type: FieldType.Int },
  FTA: { name: "FTA", type: FieldType.Int },
  FT_PCT: { name: "FT_PCT", type: FieldType.Float },
  OREB: { name: "OREB", type: FieldType.Int },
  DREB: { name: "DREB", type: FieldType.Int },
  REB: { name: "REB", type: FieldType.Int },
  AST: { name: "AST", type: FieldType.Int },
  TOV: { name: "TOV", type: FieldType.Int },
  STL: { name: "STL", type: FieldType.Int },
  BLK: { name: "BLK", type: FieldType.Int },
  BLKA: { name: "BLKA", type: FieldType.Int },
  PF: { name: "PF", type: FieldType.Int },
  PFD: { name: "PFD", type: FieldType.Int },
  PTS: { name: "PTS", type: FieldType.Int },
  PLUS_MINUS: { name: "PLUS_MINUS", type: FieldType.Int },
  NBA_FANTASY_PTS: { name: "NBA_FANTASY_PTS", type: FieldType.Float },
  DD2: { name: "DD2", type: FieldType.Int },
  TD3: { name: "TD3", type: FieldType.Int },
  WNBA_FANTASY_PTS: { name: "WNBA_FANTASY_PTS", type: FieldType.Float },
  GP_RANK: { name: "GP_RANK", type: FieldType.Int },
  W_RANK: { name: "W_RANK", type: FieldType.Int },
  L_RANK: { name: "L_RANK", type: FieldType.Int },
  W_PCT_RANK: { name: "W_PCT_RANK", type: FieldType.Int },
  MIN_RANK: { name: "MIN_RANK", type: FieldType.Int },
  FGM_RANK: { name: "FGM_RANK", type: FieldType.Int },
  FGA_RANK: { name: "FGA_RANK", type: FieldType.Int },
  FG_PCT_RANK: { name: "FG_PCT_RANK", type: FieldType.Int },
  FG3M_RANK: { name: "FG3M_RANK", type: FieldType.Int },
  FG3A_RANK: { name: "FG3A_RANK", type: FieldType.Int },
  FG3_PCT_RANK: { name: "FG3_PCT_RANK", type: FieldType.Int },
  FTM_RANK: { name: "FTM_RANK", type: FieldType.Int },
  FTA_RANK: { name: "FTA_RANK", type: FieldType.Int },
  FT_PCT_RANK: { name: "FT_PCT_RANK", type: FieldType.Int },
  OREB_RANK: { name: "OREB_RANK", type: FieldType.Int },
  DREB_RANK: { name: "DREB_RANK", type: FieldType.Int },
  REB_RANK: { name: "REB_RANK", type: FieldType.Int },
  AST_RANK: { name: "AST_RANK", type: FieldType.Int },
  TOV_RANK: { name: "TOV_RANK", type: FieldType.Int },
  STL_RANK: { name: "STL_RANK", type: FieldType.Int },
  BLK_RANK: { name: "BLK_RANK", type: FieldType.Int },
  BLKA_RANK: { name: "BLKA_RANK", type: FieldType.Int },
  PF_RANK: { name: "PF_RANK", type: FieldType.Int },
  PFD_RANK: { name: "PFD_RANK", type: FieldType.Int },
  PTS_RANK: { name: "PTS_RANK", type: FieldType.Int },
  PLUS_MINUS_RANK: { name: "PLUS_MINUS_RANK", type: FieldType.Int },
  NBA_FANTASY_PTS_RANK: { name: "NBA_FANTASY_PTS_RANK", type: FieldType.Int },
  DD2_RANK: { name: "DD2_RANK", type: FieldType.Int },
  TD3_RANK: { name: "TD3_RANK", type: FieldType.Int },
  WNBA_FANTASY_PTS_RANK: { name: "WNBA_FANTASY_PTS_RANK", type: FieldType.Int },
  CFID: { name: "CFID", type: FieldType.Int },
  CFPARAMS: { name: "CFPARAMS", type: FieldType.String },
  year: { name: "year", type: FieldType.Year },
  MIN_PerGame: { name: "MIN_PerGame", type: FieldType.Float },
  FGM_PerGame: { name: "FGM_PerGame", type: FieldType.Float },
  FGA_PerGame: { name: "FGA_PerGame", type: FieldType.Float },
  FG3M_PerGame: { name: "FG3M_PerGame", type: FieldType.Float },
  FG3A_PerGame: { name: "FG3A_PerGame", type: FieldType.Float },
  FTM_PerGame: { name: "FTM_PerGame", type: FieldType.Float },
  FTA_PerGame: { name: "FTA_PerGame", type: FieldType.Float },
  OREB_PerGame: { name: "OREB_PerGame", type: FieldType.Float },
  DREB_PerGame: { name: "DREB_PerGame", type: FieldType.Float },
  REB_PerGame: { name: "REB_PerGame", type: FieldType.Float },
  AST_PerGame: { name: "AST_PerGame", type: FieldType.Float },
  TOV_PerGame: { name: "TOV_PerGame", type: FieldType.Float },
  STL_PerGame: { name: "STL_PerGame", type: FieldType.Float },
  BLK_PerGame: { name: "BLK_PerGame", type: FieldType.Float },
  BLKA_PerGame: { name: "BLKA_PerGame", type: FieldType.Float },
  PF_PerGame: { name: "PF_PerGame", type: FieldType.Float },
  PFD_PerGame: { name: "PFD_PerGame", type: FieldType.Float },
  PTS_PerGame: { name: "PTS_PerGame", type: FieldType.Float },
  PLUS_MINUS_PerGame: { name: "PLUS_MINUS_PerGame", type: FieldType.Float },
  NBA_FANTASY_PTS_PerGame: {
    name: "NBA_FANTASY_PTS_PerGame",
    type: FieldType.Float,
  },
  MIN_Per36: { name: "MIN_Per36", type: FieldType.Float },
  FGM_Per36: { name: "FGM_Per36", type: FieldType.Float },
  FGA_Per36: { name: "FGA_Per36", type: FieldType.Float },
  FG3M_Per36: { name: "FG3M_Per36", type: FieldType.Float },
  FG3A_Per36: { name: "FG3A_Per36", type: FieldType.Float },
  FTM_Per36: { name: "FTM_Per36", type: FieldType.Float },
  FTA_Per36: { name: "FTA_Per36", type: FieldType.Float },
  OREB_Per36: { name: "OREB_Per36", type: FieldType.Float },
  DREB_Per36: { name: "DREB_Per36", type: FieldType.Float },
  REB_Per36: { name: "REB_Per36", type: FieldType.Float },
  AST_Per36: { name: "AST_Per36", type: FieldType.Float },
  TOV_Per36: { name: "TOV_Per36", type: FieldType.Float },
  STL_Per36: { name: "STL_Per36", type: FieldType.Float },
  BLK_Per36: { name: "BLK_Per36", type: FieldType.Float },
  BLKA_Per36: { name: "BLKA_Per36", type: FieldType.Float },
  PF_Per36: { name: "PF_Per36", type: FieldType.Float },
  PFD_Per36: { name: "PFD_Per36", type: FieldType.Float },
  PTS_Per36: { name: "PTS_Per36", type: FieldType.Float },
  PLUS_MINUS_Per36: { name: "PLUS_MINUS_Per36", type: FieldType.Float },
  NBA_FANTASY_PTS_Per36: {
    name: "NBA_FANTASY_PTS_Per36",
    type: FieldType.Float,
  },
  MIN_Per100Possessions: {
    name: "MIN_Per100Possessions",
    type: FieldType.Float,
  },
  FGM_Per100Possessions: {
    name: "FGM_Per100Possessions",
    type: FieldType.Float,
  },
  FGA_Per100Possessions: {
    name: "FGA_Per100Possessions",
    type: FieldType.Float,
  },
  FG3M_Per100Possessions: {
    name: "FG3M_Per100Possessions",
    type: FieldType.Float,
  },
  FG3A_Per100Possessions: {
    name: "FG3A_Per100Possessions",
    type: FieldType.Float,
  },
  FTM_Per100Possessions: {
    name: "FTM_Per100Possessions",
    type: FieldType.Float,
  },
  FTA_Per100Possessions: {
    name: "FTA_Per100Possessions",
    type: FieldType.Float,
  },
  OREB_Per100Possessions: {
    name: "OREB_Per100Possessions",
    type: FieldType.Float,
  },
  DREB_Per100Possessions: {
    name: "DREB_Per100Possessions",
    type: FieldType.Float,
  },
  REB_Per100Possessions: {
    name: "REB_Per100Possessions",
    type: FieldType.Float,
  },
  AST_Per100Possessions: {
    name: "AST_Per100Possessions",
    type: FieldType.Float,
  },
  TOV_Per100Possessions: {
    name: "TOV_Per100Possessions",
    type: FieldType.Float,
  },
  STL_Per100Possessions: {
    name: "STL_Per100Possessions",
    type: FieldType.Float,
  },
  BLK_Per100Possessions: {
    name: "BLK_Per100Possessions",
    type: FieldType.Float,
  },
  BLKA_Per100Possessions: {
    name: "BLKA_Per100Possessions",
    type: FieldType.Float,
  },
  PF_Per100Possessions: { name: "PF_Per100Possessions", type: FieldType.Float },
  PFD_Per100Possessions: {
    name: "PFD_Per100Possessions",
    type: FieldType.Float,
  },
  PTS_Per100Possessions: {
    name: "PTS_Per100Possessions",
    type: FieldType.Float,
  },
  PLUS_MINUS_Per100Possessions: {
    name: "PLUS_MINUS_Per100Possessions",
    type: FieldType.Float,
  },
  NBA_FANTASY_PTS_Per100Possessions: {
    name: "NBA_FANTASY_PTS_Per100Possessions",
    type: FieldType.Float,
  },
  E_OFF_RATING: { name: "E_OFF_RATING", type: FieldType.Float },
  OFF_RATING: { name: "OFF_RATING", type: FieldType.Float },
  sp_work_OFF_RATING: { name: "sp_work_OFF_RATING", type: FieldType.Float },
  E_DEF_RATING: { name: "E_DEF_RATING", type: FieldType.Float },
  DEF_RATING: { name: "DEF_RATING", type: FieldType.Float },
  sp_work_DEF_RATING: { name: "sp_work_DEF_RATING", type: FieldType.Float },
  E_NET_RATING: { name: "E_NET_RATING", type: FieldType.Float },
  NET_RATING: { name: "NET_RATING", type: FieldType.Float },
  sp_work_NET_RATING: { name: "sp_work_NET_RATING", type: FieldType.Float },
  AST_PCT: { name: "AST_PCT", type: FieldType.Float },
  AST_TO: { name: "AST_TO", type: FieldType.Float },
  AST_RATIO: { name: "AST_RATIO", type: FieldType.Float },
  OREB_PCT: { name: "OREB_PCT", type: FieldType.Float },
  DREB_PCT: { name: "DREB_PCT", type: FieldType.Float },
  REB_PCT: { name: "REB_PCT", type: FieldType.Float },
  TM_TOV_PCT: { name: "TM_TOV_PCT", type: FieldType.Float },
  E_TOV_PCT: { name: "E_TOV_PCT", type: FieldType.Float },
  EFG_PCT: { name: "EFG_PCT", type: FieldType.Float },
  TS_PCT: { name: "TS_PCT", type: FieldType.Float },
  USG_PCT: { name: "USG_PCT", type: FieldType.Float },
  E_USG_PCT: { name: "E_USG_PCT", type: FieldType.Float },
  E_PACE: { name: "E_PACE", type: FieldType.Float },
  PACE: { name: "PACE", type: FieldType.Float },
  PACE_PER40: { name: "PACE_PER40", type: FieldType.Float },
  sp_work_PACE: { name: "sp_work_PACE", type: FieldType.Float },
  PIE: { name: "PIE", type: FieldType.Float },
  POSS: { name: "POSS", type: FieldType.Int },
  FGM_PG: { name: "FGM_PG", type: FieldType.Float },
  FGA_PG: { name: "FGA_PG", type: FieldType.Float },
  E_OFF_RATING_RANK: { name: "E_OFF_RATING_RANK", type: FieldType.Int },
  OFF_RATING_RANK: { name: "OFF_RATING_RANK", type: FieldType.Int },
  sp_work_OFF_RATING_RANK: {
    name: "sp_work_OFF_RATING_RANK",
    type: FieldType.Int,
  },
  E_DEF_RATING_RANK: { name: "E_DEF_RATING_RANK", type: FieldType.Int },
  DEF_RATING_RANK: { name: "DEF_RATING_RANK", type: FieldType.Int },
  sp_work_DEF_RATING_RANK: {
    name: "sp_work_DEF_RATING_RANK",
    type: FieldType.Int,
  },
  E_NET_RATING_RANK: { name: "E_NET_RATING_RANK", type: FieldType.Int },
  NET_RATING_RANK: { name: "NET_RATING_RANK", type: FieldType.Int },
  sp_work_NET_RATING_RANK: {
    name: "sp_work_NET_RATING_RANK",
    type: FieldType.Int,
  },
  AST_PCT_RANK: { name: "AST_PCT_RANK", type: FieldType.Int },
  AST_TO_RANK: { name: "AST_TO_RANK", type: FieldType.Int },
  AST_RATIO_RANK: { name: "AST_RATIO_RANK", type: FieldType.Int },
  OREB_PCT_RANK: { name: "OREB_PCT_RANK", type: FieldType.Int },
  DREB_PCT_RANK: { name: "DREB_PCT_RANK", type: FieldType.Int },
  REB_PCT_RANK: { name: "REB_PCT_RANK", type: FieldType.Int },
  TM_TOV_PCT_RANK: { name: "TM_TOV_PCT_RANK", type: FieldType.Int },
  E_TOV_PCT_RANK: { name: "E_TOV_PCT_RANK", type: FieldType.Int },
  EFG_PCT_RANK: { name: "EFG_PCT_RANK", type: FieldType.Int },
  TS_PCT_RANK: { name: "TS_PCT_RANK", type: FieldType.Int },
  USG_PCT_RANK: { name: "USG_PCT_RANK", type: FieldType.Int },
  E_USG_PCT_RANK: { name: "E_USG_PCT_RANK", type: FieldType.Int },
  E_PACE_RANK: { name: "E_PACE_RANK", type: FieldType.Int },
  PACE_RANK: { name: "PACE_RANK", type: FieldType.Int },
  sp_work_PACE_RANK: { name: "sp_work_PACE_RANK", type: FieldType.Int },
  PIE_RANK: { name: "PIE_RANK", type: FieldType.Int },
  FGM_PG_RANK: { name: "FGM_PG_RANK", type: FieldType.Int },
  FGA_PG_RANK: { name: "FGA_PG_RANK", type: FieldType.Int },
  DEF_WS: { name: "Defensive Win Shares", type: FieldType.Float },
  DEF_WS_PerGame: {
    name: "Defensive Win Shares per game",
    type: FieldType.Float,
  },
  DEF_WS_Per36: { name: "Defensive Win Shares per 36", type: FieldType.Float },
  DEF_WS_Per100Possessions: {
    name: "Defensive Win Shares per 100 posessions",
    type: FieldType.Float,
  },
};
